name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest

      - name: Deploy to Heroku
        run: |
          # Install Heroku CLI
          curl https://cli-assets.heroku.com/install.sh | sh
          # Log in to Heroku container registry
          heroku container:login

          # Check if the Heroku app exists
          if ! heroku apps:info -a ${{ secrets.HEROKU_APP_NAME }} &> /dev/null; then
            echo "Creating new Heroku app: ${{ secrets.HEROKU_APP_NAME }}"
            heroku apps:create ${{ secrets.HEROKU_APP_NAME }}
            heroku stack:set container -a ${{ secrets.HEROKU_APP_NAME }}
          else
            echo "Using existing Heroku app: ${{ secrets.HEROKU_APP_NAME }}"
            # Check the current stack
            CURRENT_STACK=$(heroku stack -a ${{ secrets.HEROKU_APP_NAME }} --json | jq -r '.current')
            if [ "$CURRENT_STACK" != "container" ]; then
              echo "Switching stack to container"
              heroku stack:set container -a ${{ secrets.HEROKU_APP_NAME }}
            fi
          fi

          # Push and release the Docker image to Heroku
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
